name: Create Branch, Add Content, and Create Pull Request

on:
  workflow_dispatch:
    inputs:
      branch_name:
        description: 'Name for the new branch'
        required: true
      content:
        description: 'Content for content.txt'
        required: true

jobs:
  create-branch-and-add-content:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

    outputs:
      branch_name: ${{ steps.set_branch_info.outputs.branch_name }}
      branch_slug: ${{ steps.set_branch_info.outputs.branch_slug }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set Branch Info
        id: set_branch_info
        run: |
          BRANCH_NAME="${{ github.event.inputs.branch_name }}"
          BRANCH_SLUG=$(echo "$BRANCH_NAME" | tr '[:upper:]' '[:lower:]' | sed -e 's/ /-/g' -e 's/[^a-z0-9-]//g')
          echo "branch_name=$BRANCH_NAME" >> $GITHUB_OUTPUT
          echo "branch_slug=$BRANCH_SLUG" >> $GITHUB_OUTPUT

      - name: Create and switch to new branch
        run: |
          git checkout -b ${{ needs.create-branch-and-add-content.outputs.branch_slug }}
          git push --set-upstream origin ${{ needs.create-branch-and-add-content.outputs.branch_slug }}

      - name: Create content.txt with input content
        run: |
          printf "%s" "${{ github.event.inputs.content }}" > content.txt
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add content.txt
          git commit -m "Add content.txt with provided content"
          git push

      - name: Create Pull Request
        uses: actions/github-script@v6
        with:
          script: |
            const branchName = core.getInput('branch_name');
            const title = branchName;
            const body = 'Automatically generated pull request.';
            const base = 'main';
            const head = ${{ needs.create-branch-and-add-content.outputs.branch_name }};

            const createPr = await github.rest.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: title,
              body: body,
              head: head,
              base: base,
            });

            core.setOutput('pr_number', createPr.data.number);
          github-token: ${{ secrets.GITHUB_TOKEN }}

